# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jahzeel Vargas
title: Estudiante de Ingenieria informatica
email: ji.vargasfrias@gmail.com
website: https://github.com/JahzeelVFrias/Presentation_page

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
instagram_username: jahzeel_frias
linkedin_username: Jahzeel Vargas

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
 Hola! Mi nombre es Jahzeel, soy estudiante de ingenieria informatica en la Universidad de Guadalajara. Me gusta el desarrollo Front-end.

  I am most skilled in: <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/JahzeelVFrias
        # link_text: Project Website
        additional_links:
          - title:  JahzeelVFrias/Presentation_page
            icon: fab fa-github
            url: github.com/JahzeelVFrias/Presentation_page 
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Proyectos personales
        link: boringcompany.com
        sub_title: Estudiante
        caption: August 2021 - Present
        quote: >
          Espero pronto subir más proyectos personales
        description: | # this will include new lines to allow paragraphs
          Poco a poco :)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2021 - Present
        sub_title: Ingenieria Informatica
        quote: >
          Sobreviviendo a la vida universitaria desde 2021, cada dia más ingeniero.
        description: | # this will include new lines to allow paragraphs
          Todos los dias es increible pertenecer a la poderosisima

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Ademas de mis intereses en el desarrollo de software, estos son lagunos de mis pasatiempos:
      - Pintar
      - Gaming (League of Legends)
      - Leer libros de superación personal (Aunque no siempre los sigo jajaja)
      - [Becoming a Nakama](https://www.youtube.com/watch?v=dXAtu-Dei_o)

      Look at this little cat  
      ![Cat](/modern-resume-theme/images/709b19141eb96c7ca182ec70bac4a764.jpg "Cat")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
