# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jahzeel Vargas
title: Estudiante de Ingenieria informatica
email: ji.vargasfrias@gmail.com
website: https://github.com/JahzeelVFrias/Presentation_page

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  JahzeelVFrias
instagram_username: jahzeel_frias
linkedin_username: Jahzeel Vargas

# Additional icon links
additional_links:
- title: Presentation_Page
  icon: fas fa-globe
  url: https://jahzeelvfrias.github.io/Presentation_page/

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
 Hola! Mi nombre es Jahzeel, soy estudiante de ingenieria informatica en la Universidad de Guadalajara. Me gusta el desarrollo Front-end.

  Soy el más habil en: <mark>Eating Pizza</mark> <mark>Front-End Developer</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/JahzeelVFrias
        # link_text: Project Website
        additional_links:
          - title:  JahzeelVFrias/Presentation_page
            icon: fab fa-github
            url: github.com/JahzeelVFrias/Presentation_page 
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Aun no hay nada aquí, pero espero pronto poner algo.
        description: | # this will include new lines to allow paragraphs
         Comencé este proyecto como una forma de aprender a usar Github, tambien publicar proyectos que he hecho con HTML, CSS y Javascript

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Diseño web
        link: https://www.udg.mx/es 
        # link_text: boringcompany.com
        sub_title: Estudiante universitario
        caption: August 2023 - December 2023
        quote: >
          DEsarrollo web en HTML, CSS y Javascrript. Experiencia utilizando Firebase
        description: | # this will include new lines to allow paragraphs
        Proyecto escolar para una pagina de cursos
            

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Centro Universitario de Ciencias Exactas e Ingenierias
        caption: 2021 - Presente
        sub_title: Ingenieria Informatica
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
